### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Wolfos** [GlitchEnzo/Vapor#1]
It'd seem that your project does not have a license. Because it's on Github, it can be reasonably assumed that I'm allowed to at least look at it, but any usage should be forbidden (since you never gave permission for usage). Might I suggest adding an Apache 2.0 license?

**Comment by GlitchEnzo** [comment]
Sorry about that.

I added a license file explicitly stating that the entire project is under the MIT license.

**Comment by Wolfos** [comment]
Nice, thanks for the quick response. Was looking at the engine for some example code, it's nicely written.
